import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../ui/Card";
import { Badge } from "../ui/Badge";
import apiService from "../../services/api";
import DOMPurify from "dompurify";
import { marked } from "marked";

export default function ReportPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) {
      setError("No report ID provided.");
      setLoading(false);
      return;
    }
    apiService.getReport(id)
      .then((res: any) => {
        if (res && res.success && res.data) {
          setReport(res.data);
        } else {
          setError("Report not found.");
        }
      })
      .catch(() => setError("Failed to load report."))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        <div className="text-gray-600 mt-4">Loading report...</div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex flex-col items-center justify-center h-64">
        <div className="p-3 bg-red-100 rounded-full mb-2">
          <span className="text-red-600 font-bold">!</span>
        </div>
        <div className="text-red-600 font-medium">{error || "Report not found."}</div>
        <button
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded"
          onClick={() => navigate(-1)}
        >
          Go Back
        </button>
      </div>
    );
  }

  const inquiry = report.inquiry || {};
  const formatDate = (dateString: string) =>
    dateString
      ? new Date(dateString).toLocaleString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
          hour: "2-digit",
          minute: "2-digit",
        })
      : "";

  return (
    <div className="max-w-2xl mx-auto py-10">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl font-bold">{report.title || "AI Report"}</CardTitle>
          <CardDescription>
            <span className="mr-2">
              <Badge variant="outline" className="capitalize">{report.status || "Draft"}</Badge>
            </span>
            <span className="mr-2">
              <Badge variant="secondary" className="capitalize">{inquiry.priority || "Medium"}</Badge>
            </span>
            <span className="text-xs text-gray-500">{formatDate(report.created_at)}</span>
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <span className="font-semibold text-gray-700">Customer:</span>{" "}
            <span className="text-gray-900">{inquiry.name}</span>
          </div>
          <div>
            <span className="font-semibold text-gray-700">Company:</span>{" "}
            <span className="text-gray-900">{inquiry.company || "—"}</span>
          </div>
          <div>
            <span className="font-semibold text-gray-700">Service:</span>{" "}
            <span className="text-gray-900">{report.type || (inquiry.services || []).join(", ")}</span>
          </div>
          <div>
            <span className="font-semibold text-gray-700">Generated By:</span>{" "}
            <span className="text-gray-900">{report.generated_by || "AI Assistant"}</span>
          </div>
          <div className="mt-4">
            <span className="font-semibold text-gray-700">Report Content:</span>
            <div className="prose prose-sm max-w-none mt-2 text-gray-800">
              <div
                dangerouslySetInnerHTML={{
                  __html: DOMPurify.sanitize(marked.parse(report.content || "") as string),
                }}
              />
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}