apiVersion: v2
name: ai-consultant-chat
description: A Helm chart for AI Consultant Live Chat System
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - chat
  - ai
  - websocket
  - consulting

home: https://github.com/your-org/ai-consultant-chat
sources:
  - https://github.com/your-org/ai-consultant-chat

maintainers:
  - name: DevOps Team
    email: devops@company.com

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "15.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled